# Author: Michael Kashirin <hotmail.mkashirin@gmail.com>

"ui.background" = {}
"ui.text" = "light_gray"
"ui.text.focus" = { fg = "white", modifiers = ["bold"] }
"ui.menu" = { fg = "white" }
"ui.menu.selected" = { fg = "black", bg = "white", modifiers = ["bold"] }
"ui.popup" = { fg = "white" }
"ui.menu.scroll" = { fg = "white", bg = "comment_gray" }
"ui.bufferline" = "comment_gray"
"ui.bufferline.active" = { fg = "white", modifiers = ["bold"] }
"ui.virtual.inlay-hint" = { fg = "comment_gray" }
"ui.virtual.indent-guide" = { fg = "selection_gray" }
"ui.virtual.jump-label" = { fg = "teal", modifiers = [
  "bold",
], underline = { style = "line" } }
"ui.virtual.ruler" = { bg = "selection_gray" }
"ui.statusline" = { fg = "white" }
"ui.statusline.inactive" = { fg = "dim_gray" }
"ui.selection" = { fg = "black", bg = "white" }
"ui.selection.primary" = { fg = "black", bg = "light_gray" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.linenr" = "comment_gray"
"ui.linenr.selected" = { fg = "white", modifiers = ["bold"] }
"ui.window" = "selection_gray"

"keyword" = { fg = "white", modifiers = ["bold"] }
"function" = "white"
"type" = "light_gray"
"variable" = "light_gray"
"variable.other.member" = "light_gray"
"constant" = "white"
"string" = "dim_gray"
"comment" = { fg = "comment_gray" }
"operator" = "white"
"punctuation" = "dim_gray"
"attribute" = "light_gray"

"diagnostic.error" = { fg = "red" }
"diagnostic.warning" = { fg = "pink" }
"diagnostic.info" = { fg = "teal" }
"diagnostic.hint" = { fg = "dim_gray" }
"error" = { fg = "red", modifiers = ["bold"] }
"warning" = { fg = "pink" }
"info" = "teal"
"hint" = "dim_gray"

[palette]
black = "#000000"
selection_gray = "#3f3f3f"
comment_gray = "#888888"
dim_gray = "#999999"
light_gray = "#aaaaaa"
white = "#c1c1c1"

teal = "#486e6f"
pink = "#dd9999"
red = "#a06666"
