theme = "black_metal_opaque"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"
true-color = true
# rulers = [80, 120]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
