[[language]]
name = "python"
language-servers = ["ty"]
indent = { tab-width = 4, unit = "    " }
formatter = { command = "ruff", args = [
  "format",
  "--line-length",
  "79",
  "--quiet",
  "-",
] }
file-types = ["py", "ipynb", "pyi"]
auto-format = true

[language-server.ty]
command = "ty"
args = ["server"]

[[language]]
name = "zig"
auto-format = true
language-servers = ["zls"]
indent = { tab-width = 4, unit = "    " }
formatter = { command = "zig", args = ["fmt", "--stdin"] }

[language-server.zls]
command = "zls"
args = ["--config-path", "~/.config/zls.json"]

[[language]]
name = "c"
language-servers = ["clangd"]
indent = { tab-width = 4, unit = "    " }
auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "cpp"
file-types = ["cpp", "hpp"]
language-servers = ["clangd"]
indent = { tab-width = 4, unit = "    " }
auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "rust"
auto-format = true
language-servers = ["rust-analyzer"]
indent = { tab-width = 4, unit = "    " }
formatter = { command = "rustfmt" }

[language-server.rust-analyzer]
command = "rust-analyzer"
[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "julia"
auto-format = true
language-servers = [ "julia" ]
indent = { tab-width = 4, unit = "    " }

[language-server.julia]
command = "julia"
timeout = 60
args = [
  "--startup-file=no",
  "--history-file=no",
  "--quiet",
  "-e",
  "using LanguageServer; runserver()",
]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "markdown"
language-servers = [ "marksman", "ltex-ls" ]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "odin"
auto-format = true
roots = ["ols.json", "main.odin"]
language-servers = [ "ols" ]
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "odinfmt", args = [ "-stdin" ] }
